version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: calculBd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./Calculatrice  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000  
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./calculatrice-front  
    ports:
      - "3000:80"  

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
